### ISSUE TITLE
Permission issue in odsc_east_kg_2021-main_jupyterlab docker container

### ISSUE THREAD

**Issue by stepgazaille** [cj2001/odsc_east_kg_2021#6]
Hello,

First of all thank you for sharing this code base! It is much appreciated.

I'm trying to execute the notebooks from the odsc_east_kg_2021-main_jupyterlab docker container, however there seems to be some permissions issues. I ran the `docker-composer build`  (no error message), but I can't access any of the notebooks from inside the container: the notebooks are not visible from Jupyter Lab and I get the following error message when I run `ls` from a terminal: `ls: cannot open directory '.': Permission denied`.

I tried updating the [Dockerfile](https://github.com/cj2001/odsc_east_kg_2021/blob/main/Dockerfile) by replacing the `COPY --chown=${NB_UID}:${NB_GID} . /home/jovyan/work` line with:
```
COPY . /home/jovyan/work
RUN chmod 777  /home/jovyan/work
```
But that did not solve the issue either.

Any idea what the problem might be?

**Comment by cj2001** [comment]
When you say that you are trying to access them "from inside the container," are you logging into the container itself via something like `docker exec -it <container name> /bin/bash`?  

There should be no need to do that though once you do 

```
docker-compose build
docker-compose up
```

The container should set up the volume linking such that you can access the contents of `/notebooks` directly from your local machine.

So please let me know and we can go from there.

**Comment by ghost** [comment]
Hello,

Thank you for the quick answer!
The permission error appears when I run:
```
docker-compose build
docker-compose up
```
I notice today that it is also visible from the terminal output of the `docker-compose up` command:
```
jupyterlab_1  | [E 2021-04-01 17:20:07.037 ServerApp] Uncaught exception GET /api/nbconvert?1617297605430 (172.20.0.1)
jupyterlab_1  |     HTTPServerRequest(protocol='http', host='127.0.0.1:8888', method='GET', uri='/api/nbconvert?1617297605430', version='HTTP/1.1', remote_ip='172.20.0.1')
jupyterlab_1  |     Traceback (most recent call last):
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 1702, in _execute
jupyterlab_1  |         result = method(*self.path_args, **self.path_kwargs)
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/tornado/web.py", line 3173, in wrapper
jupyterlab_1  |         return method(self, *args, **kwargs)
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/jupyter_server/services/nbconvert/handlers.py", line 17, in get
jupyterlab_1  |         exporters = base.get_export_names()
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
jupyterlab_1  |         e = get_exporter(exporter_name)(config=config)
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
jupyterlab_1  |         if getattr(exporter(config=config), 'enabled', True):
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
jupyterlab_1  |         super().__init__(config=config, **kw)
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
jupyterlab_1  |         self._init_preprocessors()
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
jupyterlab_1  |         conf = self._get_conf()
jupyterlab_1  |       File "/opt/conda/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 509, in _get_conf
jupyterlab_1  |         if conf_path.exists():
jupyterlab_1  |       File "/opt/conda/lib/python3.8/pathlib.py", line 1400, in exists
jupyterlab_1  |         self.stat()
jupyterlab_1  |       File "/opt/conda/lib/python3.8/pathlib.py", line 1197, in stat
jupyterlab_1  |         return self._accessor.stat(self)
jupyterlab_1  |     PermissionError: [Errno 13] Permission denied: '/home/jovyan/work/conf.json'
```

**Comment by cj2001** [comment]
Very bizarre.

Can you please do me a favor and tell me the output of doing `ls -lah` for both `notebooks/` as well as the files within that subdirectory on your localhost?  For example, when I do this on my localhost I get:

```
drwxrwxr-x  5 cj2001 cj2001 4.0K Mar 30 10:52  notebooks
```
for the subdirectory and then 

```
cj-ubuntunotebooks (main)$ ls -lah
total 3.8M
drwxrwxr-x 5 cj2001 cj2001 4.0K Mar 30 10:52 .
drwxrwxr-x 6 cj2001 cj2001 4.0K Mar 30 09:21 ..
-rw-rw-r-- 1 cj2001 cj2001   41 Mar 31 14:33 .api_key
drwxrwxr-x 2 cj2001 cj2001 4.0K Mar 28 17:49 data
-rw-rw-r-- 1 cj2001 cj2001  90K Mar 30 09:29 graph_data_science.ipynb
drwxr-xr-x 2 cj2001 users  4.0K Mar 30 09:28 .ipynb_checkpoints
-rw-rw-r-- 1 cj2001 cj2001  36K Mar 30 10:09 populate_database_with_nlp.ipynb
```
on the files within that directory.

I am curious about this `conf.json`.  That is not something that should be in the container.  For example, when I do an `ls -lah` within the container at `/home/jovyan/work/` I get:

```
(base) jovyan@68a8daea5973:~/work$ ls -lah
total 3.8M
drwxrwxr-x 5 jovyan  1000 4.0K Mar 30 16:52 .
drwsrwsr-x 1 jovyan users 4.0K Apr  1 20:20 ..
-rw-rw-r-- 1 jovyan  1000   41 Mar 31 20:33 .api_key
drwxrwxr-x 2 jovyan  1000 4.0K Mar 28 23:49 data
-rw-rw-r-- 1 jovyan  1000  90K Mar 30 15:29 graph_data_science.ipynb
drwxr-xr-x 2 jovyan users 4.0K Mar 30 15:28 .ipynb_checkpoints
-rw-rw-r-- 1 jovyan  1000  36K Mar 30 16:09 populate_database_with_nlp.ipynb
```

So I don't have a `conf.json` file in that container.  Can you, by chance, share the contents of that file here as well?

**Comment by ghost** [comment]
Ah! Nevermind, I found the issue: I forgot to run `chmod` with the `-R` switch when I updated the permission on my local copy of the repository, so the subdirectories (including `notebooks`) had the wrong permissions...

Thank you for your help and sorry to bother you with that...

**Comment by cj2001** [comment]
No worries!  I am glad you were able to find the problem! Please feel free to reach out again if it gives you more problems.
